<?php
require_once __DIR__ . '/guard.php';

// Load constants for BASE_URL (constants.php has no DB dependency, safe to load)
require_once __DIR__ . '/../config/constants.php';

// Check if we have database credentials and admin info
if (!isset($_SESSION['install_db']) || !isset($_SESSION['install_admin'])) {
    header('Location: step1.php');
    exit;
}

$creds = $_SESSION['install_db'];
$admin = $_SESSION['install_admin'];

// Write config/db.php
$configContent = "<?php
// Database Configuration
// Generated by installer on " . date('Y-m-d H:i:s') . "

define('DB_HOST', '{$creds['host']}');
define('DB_PORT', '{$creds['port']}');
define('DB_NAME', '{$creds['dbname']}');
define('DB_USER', '{$creds['user']}');
define('DB_PASS', '{$creds['pass']}');

try {
    \$dsn = \"mysql:host=\" . DB_HOST . \";port=\" . DB_PORT . \";dbname=\" . DB_NAME . \";charset=utf8mb4\";
    \$options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ];
    
    \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
} catch (PDOException \$e) {
    die(\"Database connection failed: \" . \$e->getMessage());
}
";

$configFile = __DIR__ . '/../config/db.php';
if (file_put_contents($configFile, $configContent) === false) {
    die('Failed to write config/db.php. Please ensure the config folder is writable.');
}

// Create installed.lock
$lockContent = "Installed on: " . date('Y-m-d H:i:s') . "\nDo not delete this file unless you intend to reinstall.";
$lockFile = __DIR__ . '/../config/installed.lock';
if (file_put_contents($lockFile, $lockContent) === false) {
    die('Failed to create installed.lock. Please ensure the config folder is writable.');
}

// Clear session data
unset($_SESSION['install_db']);
unset($_SESSION['install_admin']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installation Complete - Audit Management CMS</title>
    <link rel="stylesheet" href="assets/installer.css">
</head>
<body>
    <div class="installer-container">
        <div class="installer-header">
            <h1>🎉 Installation Complete!</h1>
            <p>Your Audit Management CMS is ready</p>
        </div>
        
        <div class="progress-steps">
            <div class="step completed">
                <span class="step-number">✓</span>
                <span>Requirements</span>
            </div>
            <div class="step completed">
                <span class="step-number">✓</span>
                <span>Database</span>
            </div>
            <div class="step completed">
                <span class="step-number">✓</span>
                <span>Import</span>
            </div>
            <div class="step completed">
                <span class="step-number">✓</span>
                <span>Admin</span>
            </div>
            <div class="step completed">
                <span class="step-number">✓</span>
                <span>Done</span>
            </div>
        </div>
        
        <div class="installer-body" style="text-align: center;">
            <div class="success-icon">✓</div>
            
            <h2 style="margin-bottom: 20px; color: #f1f5f9;">Your Audit Management CMS has been installed successfully!</h2>
            
            <div class="alert alert-success" style="text-align: left;">
                <strong>Admin Login Credentials:</strong><br>
                Username: <strong><?php echo htmlspecialchars($admin['username']); ?></strong><br>
                Password: <em>(the password you set in the previous step)</em>
            </div>
            
            <div class="security-warning">
                <h3>⚠️ Security Warning</h3>
                <p>
                    For security reasons, please <strong>DELETE the /install folder</strong> from your server now. Leaving it accessible could allow someone to attempt to reinstall or reset your application.
                </p>
            </div>
            
            <div style="margin-top: 30px;">
                <a href="<?php echo BASE_URL; ?>/modules/auth/login.php" class="btn btn-primary btn-block">
                    Go to Login Page →
                </a>
            </div>
        </div>
        
        <div class="installer-footer">
            Audit Management CMS Installer v1.0
        </div>
    </div>
</body>
</html>
